# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Test Flight"
  # Deletes files archives as result
  before_all do
      sh(command: "rm -vfr ~/Library/Developer/Xcode/Archives/*")
      clear_derived_data()
      xcode_select("/Applications/Xcode.app")
  end

  # release build
  lane :release do
    match(type: "appstore", 
          app_identifier: "mobile.duc..cicd-example",
          readonly: is_ci)
    increment_build_number(xcodeproj: "cicd-example.xcodeproj")
    build_app(
      disable_xcpretty: true,
      scheme: "cicd-example",
      export_method: "app-store"
    )
    upload_to_testflight
  end

  # Deletes files created as result of running gym, cert, sigh or download_dsyms
  after_all do |lane|
      clean_build_artifacts
  end
  ## fortest haha
end
