name: GitHub Actions
on:
  push:
    branches: [master]

jobs:
  builds:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build and test
        run: fastlane ios release build --env
