name: Master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Release
    runs-on: self-hosted
    env:
      PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
      LC_ALL: en_US.UTF-8
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Release
        run: |
          fastlane ios release build --env
